name = "PyTesseractDecoder"
uuid = "cb7393ab-d93b-4096-98de-53f8be4e08d3"
version = "0.1.1"
authors = ["Stefan Krastanov <stefan@krastanov.org>"]

[deps]
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
PythonCall = "0.9.16"
julia = "1.12"
